- name: ensure apache2 stop
  become: yes
  apt: name=apache2 state=present

- name: stop apache2
  become: yes
  service:
    name: apache2
    state: stopped

- name: ensure nginx is at the latest version
  become: yes
  apt: name=nginx state=latest

- name: Add nginx config template to the Nginx available sites
  become: yes
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-available/{{ server_name }}.conf

- name: Enable nginx config template from Nginx available sites
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
    state: link

- name: Add enabled Nginx site to /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ server_name }}"
    line: "127.0.0.1 {{ server_name }}"

- name: Create project directory and set its permissions
  become: yes
  file:
    path: "{{ nginx_web_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: start nginx
  become: yes
  service:
    name: nginx
    state: started
